baseURL = "https://blog.pitchpat.ch"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "pitch patch"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true
disqusShortname = 'pitchpatch'

[pagination]
  pagerSize = 5

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addDot = false
  addFrame = false
  black = "#0f0e12"
  red = "#FF6969"
  blue = "#0087E0"
  green = "#619B8A"
  yellow = "#FABC3C"
  baseColor = "#f0f1ed"
  baseOffsetColor = "#0F0F0F"
  textColor = "#666"
  description = "pitch patch blog"

[taxonomies]
  category = 'category'
  tag = 'tags'

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[[menu.social]]
     name = "youtube"
     weight = 50
     url = "https://www.youtube.com/pitchpatch?sub_confirmation=1"
     post = "<span class='alert'>New!</span>"

[[menu.social]]
    name = "instagram"
     weight = 60
     url = "https://pitchpat.ch/instagram"
     post = "<span class='alert'>New!</span>" 